services:
  coworld-mtg:
    image: coworld-mtg:latest
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.coworld
  commissioner:
    image: coworld-mtg-commissioner:latest
    platform: linux/amd64
    build:
      context: .
      dockerfile: commissioner.Dockerfile
