from pathlib import Path
import json,hashlib,copy,datetime
out=Path('/home/ubuntu/coworld-migration-20260904/hushbringer-v10-review-fixes')
h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def load(n):return json.loads((out/n).read_text())
def dump(n,a):(out/n).write_text(json.dumps(a,indent=2)+'\n')
def supersedes(n,reason):return {'path':str(out/n),'sha256':h(out/n),'reason':reason,'prior_bytes_preserved':True}
current={'constructor_audit':'manual-constructor-boundary-audit-final.json','callsite_map':'production-entry-callsite-map-final.json','native_library_map':'native-library-public-map.json','common_boundary_map':'typed-common-boundary-map-final.json','maintainer_matrix':'production-path-maintainer-map-v10-final.json','cr_audit':'cr-complete-audit.json','source_lineage':'frozen-source/lineage.json','verification':'verification-summary.json','canonical':'canonical-integration-receipt.json'}
a=load('production-entry-callsite-map.json');old_siblings=a['native_unaffected_siblings'];native=load('native-library-public-map.json')['rows'];a['native_unaffected_siblings']=[]
for r in native:
 row=copy.deepcopy(r);row['first_branch']=r['first_reaching_branch'];row['selected_authority']=r['authority'];row['test']=r['tests'][0];row['classification']='Public source-unaffected native sibling; not counted as a physical mutation kill';row['status']='Required public branch/order/rejection/event/continuation controls verified';a['native_unaffected_siblings'].append(row)
a['status']='All 51 source call sites mapped; all three native placement arms have verified natural public controls for Hand, direct Library and Dig-tracked Library. No native control obligation remains unresolved.'
a['supersedes']=supersedes('production-entry-callsite-map.json','Interim call_sites had current native links, but duplicated native_unaffected_siblings and top-level status were stale. This final version replaces every stale sibling/status and is authoritative.');a['authoritative_maps']=current;a['historical_method']=a['method'];a['method']='Complete production owner/member/leaf/barrier call-site inventory with exact current source locations, historical physical mutation links and three fully populated native source-unaffected sibling rows. Repeated native summary rows are reconciled against native-library-public-map.json.'
assert len(a['native_unaffected_siblings'])==3 and all(r['tests'] and r['test'] for r in a['native_unaffected_siblings']);dump('production-entry-callsite-map-final.json',a)
a=load('typed-common-boundary-map.json');r=next(x for x in a['rows'] if x['id']=='manual-event-constructors');r['production_entry']='Three production ZoneChangeRecord constructor expressions: filter.rs:1402 synthetic LKI, game_object.rs:1499 live-object snapshot, stack.rs:2495 synthetic token probe. Complete final audit also records 79 test expressions (including one Self), 81 named literal expressions total, and all 11 nonconstructor raw occurrences.';r['first_reaching_branch']='Production filter LKI conversion, live GameObject snapshot creation, and stack token-spec probe construction each initialize None. Test-only constructors and struct updates are categorized separately; function return signatures, documentation and golden strings are not constructors.';r['constructor_audit']='manual-constructor-boundary-audit-final.json';a['supersedes']=supersedes('typed-common-boundary-map.json','Replace stale All83/manual-constructor reference with the final exact production/test/Self/nonconstructor categories.');a['authoritative_maps']=current;dump('typed-common-boundary-map-final.json',a)
a=load('production-path-maintainer-map-v10.json');a['historical_prior_unresolved_review_items']=a.pop('unresolved_review_items');a['unresolved_review_items']=[];a['historical_full_source_lineage']=a.pop('full_source_lineage');a['full_source_lineage']={'path':str(out/'frozen-source/lineage.json'),'sha256':h(out/'frozen-source/lineage.json')};a['historical_final_verification']=a.pop('final_verification');a['final_verification']={'path':str(out/'verification-summary.json'),'binding':'Exact bytes bound by final handoff manifest once all gates complete; historical gate receipt above is not final-source execution evidence.'};a['authoritative_maps']=current;a['supersedes']=supersedes('production-path-maintainer-map-v10.json','Current review-obligation and verification references now select final maps and final-source verification. Historical earlier unresolved-items/verification references remain explicitly historical.');a['status']='All 67 historical physical mutation rows retained with original build identities. Review gaps are addressed by full native public controls and complete CR audit; the authoritative final maps select corrected constructor categories. Final verification is bound separately; known rules/baseline limitations remain.';dump('production-path-maintainer-map-v10-final.json',a)
(out/'production-path-maintainer-map-v10-final.md').write_text('Complete final production path matrix. This supersedes the interim matrix metadata; historical mutation evidence is unchanged. Current maps are listed below. Three native placement siblings have real public controls with no mutation-kill claim. The complete constructor audit contains three production and79 test expressions.\n\n'+json.dumps(current,indent=2)+'\n\n'+ '\n'.join('## '+r['id']+'\n\n'+json.dumps(r,indent=2)+'\n' for r in a['rows']))
report={'utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'source_unchanged':True,'interim_bytes_preserved':True,'corrections':['Replaced three stale native_unaffected_siblings and stale status in versioned final callsite map. Exact tests/branches now agree with native-library-public-map.json.','Replaced stale All83 manual-constructor reference in final common-boundary map. Final constructor audit distinguishes actual Self literal from enclosing excerpt.','Moved prior unresolved-review and verification references to historical metadata; current maintainer/map references consistently select final artifacts.'],'authoritative_maps':current,'new_files':{n:h(out/n) for n in ['production-entry-callsite-map-final.json','typed-common-boundary-map-final.json','production-path-maintainer-map-v10-final.json','production-path-maintainer-map-v10-final.md','manual-constructor-boundary-audit-final.json']}}
dump('final-map-corrections.json',report)
print(json.dumps(report,indent=2))
