from pathlib import Path
import json,hashlib,datetime
out=Path('/home/ubuntu/coworld-migration-20260904/hushbringer-v10-review-fixes');root=Path('/home/ubuntu/repos/phase-verifiable-loop');h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def load(n):return json.loads((out/n).read_text())
def dump(n,a):(out/n).write_text(json.dumps(a,indent=2)+'\n')
finding={'id':'remaining-native-choice-cr-citation','file':'crates/engine/src/game/engine_resolution_choices.rs','line':3528,'cited_rule':'115.1','status':'outstanding; no source edit in this frozen evidence package','problem':'CR 115.1 describes targets announced when placing a spell/ability on the stack; this comment describes non-targeted resolution-time choices. CR 608.2d is the relevant choice-timing rule, or the unrelated label can be removed.','fresh_review_source':'Root relayed the fresh independent reviewer finding during final verification; executor re-read both exact rule texts and agrees.','source_manifest_sha256':'fdc9dac52471ca15ab794f43d8f0f2608abab27af3b33e84581860e6105c7b86','next_action':'Root waits for complete independent review and dispatches a fresh fix executor. Preserve this source, executable and measured evidence.'}
a=load('cr-complete-audit.json');r=next(r for r in a['annotations'] if r['file']==finding['file'] and r['line']==3528);r['semantic_assessment']='REJECTED by fresh independent review: 115.1 describes announced targets, not this non-targeted resolution-time choice. Frozen source is unchanged. Use 608.2d or remove the label in the next fresh fix.';r['review_status']='outstanding citation finding';a['outstanding_findings']=[finding];a['semantic_review']='Supersedes the earlier blanket semantic acceptance. Original five citation groups were corrected, but the fresh reviewer identified one remaining citation at3528; no clean CR gate or implementation acceptance is claimed.';a['supersedes']={'path':str(out/'cr-complete-audit.json'),'sha256':h(out/'cr-complete-audit.json'),'correction':'Prior row184 incorrectly validated CR115.1. This complete version preserves all185 source annotations but rejects that row.'};a['rules']['608.2d']=[l for l in (root/'docs/MagicCompRules.txt').read_text().splitlines() if l.startswith('608.2d ')];dump('cr-reviewed-audit.json',a)
(out/'cr-reviewed-audit.md').write_text('The frozen source has one outstanding CR citation finding at engine_resolution_choices.rs:3528. CR115.1 describes announced targets; the native selection occurs during resolution, for which CR608.2d is relevant. The source has not been changed. This supersedes the blanket semantic acceptance in cr-complete-audit.json/md, including row184. The complete reviewed JSON retains all185 added/moved/adjacent annotations and original five-group corrections. A fresh fix executor must address the remaining citation after the complete independent review.\n')
selected=load('final-map-corrections.json')['authoritative_maps'];selected.update({'callsite_map':'production-entry-callsite-map-reviewed.json','common_boundary_map':'typed-common-boundary-map-reviewed.json','maintainer_matrix':'production-path-maintainer-map-v10-reviewed.json','cr_audit':'cr-reviewed-audit.json'})
for old,new in [('production-entry-callsite-map-final.json','production-entry-callsite-map-reviewed.json'),('typed-common-boundary-map-final.json','typed-common-boundary-map-reviewed.json'),('production-path-maintainer-map-v10-final.json','production-path-maintainer-map-v10-reviewed.json')]:
 a=load(old);a['authoritative_maps']=selected;a['review_status']='Native runtime controls and original five CR groups addressed; one newly reported source citation remains outstanding. No clean implementation verdict.';a['supersedes_after_fresh_review']={'path':str(out/old),'sha256':h(out/old),'reason':'Select the complete CR audit with the outstanding115.1 finding; source/test/path evidence unchanged.'}
 if 'maintainer' in new:
  a['unresolved_review_items']=[finding];a['status']=a['review_status']
 dump(new,a)
 if 'maintainer' in new:(out/'production-path-maintainer-map-v10-reviewed.md').write_text('Current reviewed production matrix: one source citation remains outstanding. This supersedes the prior final matrix review status while preserving all67 historical mutation records and native control results. Current selected maps:\n\n'+json.dumps(selected,indent=2)+'\n\n'+ '\n'.join('## '+r['id']+'\n\n'+json.dumps(r,indent=2)+'\n' for r in a['rows']))
dump('reviewed-map-selection.json',{'utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'authoritative_maps':selected,'outstanding_findings':[finding],'prior_interim_and_final_versions_preserved':True,'source_changed':False,'review_instruction':'This reviewed selection is authoritative for the final sealed executor handoff. It supersedes prior clean-CR or no-unresolved-items metadata; native-test and physical-mutation evidence is unchanged.'})
print(json.dumps(selected,indent=2))
