import { array, label, object, string, type Fields } from "../model";
import { caseRecord, caseReports, count, fittingStatus, momentKey, momentTitle, observationMoments, observationRows, records, selectedReport, supportedTrace, type FittingContext, type FittingSelection, type LocatedRecord, type ReadArtifact } from "./model";

export interface FittingHelpers { read: ReadArtifact; artifact: (id: unknown, title?: string) => string; integrity: (id: string) => string; caseTitle: (id: string) => string }
const esc = (value: unknown) => String(value ?? "").replace(/[&<>"']/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]!);
const clipped = (value: string, max = 400) => value.length > max ? value.slice(0, max) + `… (${value.length - max} more characters in artifact)` : value;
const valueText = (value: unknown): string => value === undefined || value === null ? "Not recorded" : typeof value === "string" ? value || "Empty text" : Array.isArray(value) ? value.length ? value.map(v => typeof v === "string" ? v : JSON.stringify(v)).join(" · ") : "Empty list" : typeof value === "object" ? JSON.stringify(value) : String(value);
const val = (value: unknown, max = 500) => esc(clipped(valueText(value), max));
const integer = (value: unknown) => count(value) === null ? "—" : String(value);
const pill = (value: unknown, kind = "") => `<span class="fit-pill ${esc(kind)}">${esc(label(value))}</span>`;
const missing = (id: unknown, what: string, h: FittingHelpers) => `<div class="fit-missing"><strong>${esc(what)} ${id ? "unavailable" : "not recorded"}</strong><p>${id ? "Load or restore the referenced artifact to inspect this evidence. Missing or corrupt bytes are not a result." : "This execution has no referenced artifact for this part of the record."}</p>${id ? h.integrity(string(id)) + h.artifact(id, "Inspect evidence availability") : ""}</div>`;
const metricTitle = (name: string, column: string) => ({ hand: "Cards in hand", hand_count: "Cards in hand (count)", lands: "Lands in play", creatures: "Creatures in play", non_creatures: "Noncreatures in play", drawn: "Cards drawn", drawn_or_tutored_count: "Cards drawn or tutored (count)", land_played: "Lands played", creature_cast: "Creatures cast", instant_sorcery_cast: "Instants and sorceries cast", life: "Life total" }[name] ?? (label(name) || column.replace(/^(user|oppo)_turn_\d+_/, "").replace(/^eot_(user|oppo)_/, "").replace(/^(user|oppo)_/, "").replaceAll("_", " ")));
const actionTitle = (action: unknown, state?: unknown) => {
  const a = object(action), type = string(a.type).replace(/([a-z])([A-Z])/g, "$1 $2");
  const data = object(a.data), id = data.source_id ?? data.object_id;
  const cards = records(object(state).players).flatMap(p => [...records(p.hand), ...records(p.battlefield)]);
  const name = cards.find(card => card.object_id === id)?.name;
  return (type || "Recorded action") + (name ? " · " + string(name) : "");
};
const zone = (value: unknown) => !Array.isArray(value) ? "Not recorded" : !value.length ? "Empty" : value.slice(0, 30).map(card => esc(string(object(card).name) || "Unnamed / unknown card")).join(" · ");
function renderState(value: unknown): string {
  const state = object(value), players = records(state.players);
  if (players.length) return `<p class="fit-state-turn">${state.turn_owner === 0 ? "User" : state.turn_owner === 1 ? "Opponent" : "Active player"} · turn ${val(state.turn_number)} · ${val(state.phase)} · stack ${val(state.stack_count)}</p>${players.slice(0, 2).map(player => `<section class="fit-player-state"><h6>${player.seat === 0 ? "User" : player.seat === 1 ? "Opponent" : "Player"}<span>${val(player.life)} life</span></h6><dl class="fit-state"><dt>Hand</dt><dd>${zone(player.hand)}</dd><dt>Battlefield</dt><dd>${zone(player.battlefield)}</dd><dt>Library / graveyard</dt><dd>${val(player.library_count)} / ${val(player.graveyard_count)} cards</dd></dl>${array(player.hand).length > 30 || array(player.battlefield).length > 30 ? '<p class="fit-subtle">Zone lists show at most 30 cards. All cards remain in the trace.</p>' : ""}</section>`).join("")}`;
  const entries = Object.entries(state).slice(0, 16);
  if (!entries.length) return '<p class="fit-subtle">State projection not recorded.</p>';
  return `<dl class="fit-state">${entries.map(([key, value]) => `<dt>${esc(label(key))}</dt><dd>${val(value, 650)}</dd>`).join("")}</dl>${Object.keys(state).length > 16 ? '<p class="fit-subtle">Showing 16 state fields. The trace artifact retains all fields.</p>' : ""}`;
}
function coverageText(value: unknown): string {
  const c = object(value);
  return ["enforced", "unsupported", "informational"].map(kind => `${Array.isArray(c[kind]) ? array(c[kind]).length : "unrecorded"} ${kind}`).join(" · ");
}
function reportName(report: LocatedRecord): string { return `${label(report.value.label) || "Recorded measurement"} · ${integer(object(report.value.summary).cases)}/${integer(object(report.value.summary).planned_cases)} games · ${string(report.value.build_id).slice(0, 10) || report.id.slice(0, 10)}`; }

export function renderFitting(context: FittingContext, caseId: string, selection: FittingSelection, h: FittingHelpers): string | null {
  const report = selectedReport(context, caseId, selection.reportId);
  if (!report) return null;
  const item = caseRecord(report, caseId), constraints = h.read(item.constraints_id), result = h.read(item.result_id);
  const hasResult = result.schema === "coworld-17lands-guided-fit-v1";
  const scope = object(report.value.scope), reports = caseReports(context, caseId);
  const issues = records(report.value.issues), caseIssues = issues.filter(i => records(i.origins).some(o => o.case_id === caseId));
  const status = hasResult ? result.status : item.status;
  const countedKeys = records(constraints.milestones), keys = observationMoments(constraints), fitted = count(result.milestones_fitted);
  const last = fitted !== null && fitted > 0 && fitted <= countedKeys.length ? countedKeys[fitted - 1] : null;
  const next = fitted !== null && fitted < countedKeys.length ? countedKeys[fitted] : null;
  const moment = selection.moment >= 0 && selection.moment < keys.length ? selection.moment : Math.max(0, keys.findIndex(k => momentKey(k) === momentKey(last)));
  const trace = supportedTrace(result);
  const failure = object(trace?.failure);
  return `<section class="fitting-view" aria-label="Recorded game fitting">
    <div class="fit-head"><div><p class="eyebrow">17LANDS · RECORDED GAME FITTING</p><h3>${esc(fittingStatus(status))}</h3></div><label class="fit-report-label">Measurement<select id="fit-report-select">${reports.map(r => `<option value="${esc(r.id)}" ${r.id === report.id ? "selected" : ""}>${esc(reportName(r))}</option>`).join("")}</select></label></div>
    <p class="fit-subtle">${integer(object(report.value.summary).cases)} / ${integer(object(report.value.summary).planned_cases)} planned games measured · ${report.value.complete === true ? "Cohort measurement complete" : "Cohort measurement in progress"}</p>
    <p class="fit-lead">Does a legal engine path explain the selected observations? This record compares a supported projection of the source under the stated setup assumptions.</p>
    <div class="fit-stats"><div><strong>${integer(result.milestones_fitted)} / ${integer(result.milestones_total)}</strong><span>player-specific milestones reached</span></div><div><strong>${integer(result.fully_covered_milestones)}</strong><span>fully covered milestones</span></div><div><strong>${caseIssues.length}</strong><span>recorded issue groups for this game</span></div><div><strong>${integer(result.nodes)}</strong><span>search nodes used</span></div></div>
    <aside class="fit-scope"><strong>Scope of this result</strong><p>A supported projection match is not a complete game reconstruction, a proof of card implementation, or acceptance of a repair. Unknown and unsupported fields remain outside the checked projection.</p></aside>
    <div class="fit-provenance">${pill(report.value.label)}<span>Source row ${val(item.source_row_index)}</span><span>Execution ${val(item.execution_id)}</span>${h.artifact(report.id, "Discovery report")}${h.artifact(item.result_id, "Result & trace")}${item.result_id ? h.integrity(string(item.result_id)) : ""}</div>
    ${hasResult ? `<div class="fit-moments-summary"><div><span>Last matching moment</span><strong>${last ? esc(momentTitle(last)) : "No matched moment recorded"}</strong></div><div><span>Next selected target</span><strong>${next ? esc(momentTitle(next)) : fitted !== null && fitted === countedKeys.length && countedKeys.length ? "Selected supported milestones reached" : "Not recorded"}</strong></div></div>` : missing(item.result_id, "Fitter result", h)}
    ${status !== "matched_supported_projection" && caseIssues.length ? `<aside class="fit-stop"><strong>Recorded reason this case needs attention</strong><ul>${caseIssues.slice(0, 5).map(i => `<li>${val(i.title, 1400)}</li>`).join("")}</ul><p>Full origins and evidence appear in the issue groups below.</p></aside>` : ""}
    ${Object.keys(constraints).length ? renderObservations(constraints, result, keys, moment, selection.allFields, trace !== null, h, item.constraints_id) : missing(item.constraints_id, "Source constraints", h)}
    ${hasResult ? renderPath(result, selection.transition, h, item.result_id) : ""}
    ${renderFailure(failure)}
    <details class="fit-assumptions"><summary>Setup assumptions, budget and scope</summary><ul>${array(result.assumptions ?? constraints.assumptions).slice(0, 20).map(a => `<li>${val(a, 2000)}</li>`).join("")}</ul><dl class="fit-budget"><dt>Selected turn pairs</dt><dd>${integer(scope.turn_pairs)}</dd><dt>Node limit</dt><dd>${integer(object(result.limits).nodes ?? scope.nodes)}</dd><dt>Action limit per path</dt><dd>${integer(object(result.limits).max_actions ?? scope.max_actions)}</dd><dt>Worker deadline</dt><dd>${scope.deadline_seconds === undefined ? "Not recorded" : val(scope.deadline_seconds) + " seconds"}</dd><dt>Worker memory limit</dt><dd>${typeof scope.memory_bytes === "number" ? (scope.memory_bytes / 2 ** 30).toFixed(1) + " GiB" : "Not recorded"}</dd><dt>Search time</dt><dd>${typeof result.elapsed_millis === "number" ? (result.elapsed_millis / 1000).toFixed(3) + " seconds" : "Not recorded"}</dd><dt>Recorded seed</dt><dd>${val(result.seed)}</dd></dl>${h.artifact(report.value.build_id, "Build identity")}${h.artifact(item.constraints_id, "Full source constraints")}</details>
    ${renderIssues(report, caseId, h)}${renderFittingComparison(context, caseId, h)}
  </section>`;
}

function renderObservations(constraints: Fields, result: Fields, keys: Fields[], moment: number, all: boolean, hasTrace: boolean, h: FittingHelpers, constraintsId: unknown): string {
  const milestone = records(supportedTrace(result)?.milestones).find(m => momentKey(m.key) === momentKey(keys[moment]));
  const rows = keys[moment] ? observationRows(constraints, result, keys[moment]) : [];
  const filtered = all ? rows : rows.filter(row => row.disposition === "enforced");
  return `<section class="fit-observations"><div class="fit-section-title"><h4>Source observation beside engine projection</h4>${h.artifact(constraintsId, "Source fields")}</div>${keys.length ? `<label class="fit-moment-label">Observation moment<select id="fit-moment-select">${keys.slice(0, 100).map((key, index) => `<option value="${index}" ${index === moment ? "selected" : ""}>${esc(momentTitle(key))}</option>`).join("")}</select></label>` : '<p>No supported observation moments were recorded.</p>'}
    <div class="fit-field-controls"><button data-fit-fields="all" class="${all ? "active" : ""}" aria-pressed="${all}">All fields at this moment</button><button data-fit-fields="enforced" class="${!all ? "active" : ""}" aria-pressed="${!all}">Enforced fields</button><span>${filtered.length} fields</span></div>
    ${hasTrace && milestone?.state_position === "before_transition" ? `<p class="fit-subtle">This observation was compared before transition ${typeof milestone.transition_index === "number" ? milestone.transition_index + 1 : "(index not recorded)"}. ${count(milestone.transition_index) !== null && Number(milestone.transition_index) < records(supportedTrace(result)?.transitions).length ? `<button class="text-button" data-fit-step="${milestone.transition_index}">Inspect this boundary action</button>` : ""}</p>` : ""}
    ${!hasTrace ? '<p class="fit-trace-note">This older receipt did not record expected/actual trace comparisons. Source constraints are available; engine values are not reconstructed by the viewer.</p>' : '<p class="fit-subtle">Comparison labels and engine values come from the recorded fitter trace.</p>'}
    <div class="fit-table-wrap"><table class="fit-observation-table"><thead><tr><th>Recorded source field</th><th>Expected from source</th><th>Engine projection</th><th>Recorded comparison</th></tr></thead><tbody>${filtered.slice(0, 100).map(row => `<tr class="fit-comparison-${esc(row.comparison)}"><th scope="row"><strong>${esc(metricTitle(row.projection, row.column))}</strong><details><summary>${esc(row.disposition || "Unspecified disposition")} · source detail</summary><code>${esc(row.column)}</code><p>Raw: ${row.raw === "" ? "Blank (unknown)" : val(row.raw, 1500)}</p><p>${val(row.reason, 1000)}</p></details></th><td>${row.disposition === "informational" && !row.raw ? "Unknown" : val(row.expected)}</td><td>${val(row.actual)}${Object.keys(row.diagnostic).length ? `<aside class="fit-diagnostic"><strong>Unchecked native diagnostic</strong><p>${esc(label(row.diagnostic.metric))}: ${val(row.diagnostic.value)}</p><p>${val(row.diagnostic.limitation, 1500)}</p></aside>` : ""}</td><td>${pill(row.comparison, row.comparison)}</td></tr>`).join("") || '<tr><td colspan="4">No fields in this selection.</td></tr>'}</tbody></table></div>${filtered.length > 100 ? `<p class="fit-subtle">Showing 100 of ${filtered.length} fields; full data remains in the source artifact.</p>` : ""}
  </section>`;
}
function renderPath(result: Fields, selectedTransition: number, h: FittingHelpers, resultId: unknown): string {
  const trace = supportedTrace(result), transitions = records(trace?.transitions), legacy = records(result.witness);
  const index = selectedTransition >= 0 && selectedTransition < transitions.length ? selectedTransition : Math.max(0, transitions.length - 1);
  const step = transitions[index];
  return `<section class="fit-path"><div class="fit-section-title"><h4>Recorded engine path</h4>${trace ? pill(trace.path_kind) : pill("witness actions only")}</div><p class="fit-subtle">${trace ? "Inspect a retained transition. Names in reconstructed hidden zones describe the search hypothesis, not observed opponent cards. This path does not expose all branches explored by the search." : "Action identities were retained. State projections and per-step events were not recorded in this receipt."}</p>
    ${step ? `<label class="fit-transition-label">Transition<select id="fit-transition-select">${transitions.slice(0, 512).map((t, i) => `<option value="${i}" ${i === index ? "selected" : ""}>${i + 1}. ${t.seat === 0 ? "User" : t.seat === 1 ? "Opponent" : "Player"} · ${esc(actionTitle(t.action, t.before))}</option>`).join("")}</select></label><div class="fit-path-controls"><button data-fit-step="${Math.max(0, index - 1)}" ${index === 0 ? "disabled" : ""}>Previous action</button><span>${index + 1} / ${transitions.length}</span><button data-fit-step="${Math.min(transitions.length - 1, index + 1)}" ${index === transitions.length - 1 ? "disabled" : ""}>Next action</button></div><div class="fit-state-grid"><article><h5>Before action</h5>${renderState(step.before)}</article><article><h5>After action</h5>${renderState(step.after)}</article></div><details class="fit-action-details"><summary>${esc(actionTitle(step.action, step.before))} · action and emitted events</summary><pre>${val(step.action, 6000)}</pre><ol>${array(step.events).slice(0, 60).map(event => `<li>${val(event, 1200)}</li>`).join("")}</ol>${array(step.events).length > 60 ? '<p>Showing 60 events. Inspect the trace artifact for the complete transition.</p>' : ""}</details>` : legacy.length ? `<details class="fit-action-details"><summary>${legacy.length} retained witness actions</summary><ol>${legacy.slice(0, 512).map(a => `<li><strong>${a.seat === 0 ? "User" : "Opponent"} · ${esc(actionTitle(a.action))}</strong><code>${val(a.action, 600)}</code></li>`).join("")}</ol></details>` : '<p class="fit-trace-note">No engine path was recorded for this execution.</p>'}${h.artifact(resultId, "Complete result and path")}</section>`;
}
function renderFailure(failure: Fields): string {
  if (!Object.keys(failure).length) return "";
  const attempt = object(failure.attempt), attemptedAction = attempt.action ?? object(failure.attempted_action).action;
  return `<details class="fit-failure" open><summary>Retained unsuccessful branch</summary><p>${val(failure.detail, 2000)}</p><p class="fit-subtle">This is a separate search branch, not the displayed witness. Its action indices belong to its own predecessor path. One retained failure does not prove incompatibility.</p>${attemptedAction ? `<p><strong>Attempt: ${esc(actionTitle(attemptedAction, attempt.before ?? failure.state))}</strong></p>` : ""}${records(failure.milestones).slice(0, 4).map(m => `<h5>${esc(momentTitle(m.key))}</h5><div class="fit-table-wrap"><table class="fit-observation-table"><thead><tr><th>Source field</th><th>Expected</th><th>Engine projection</th><th>Recorded comparison</th></tr></thead><tbody>${records(m.fields).slice(0, 100).map(f => `<tr><th>${esc(metricTitle(string(f.projection), string(f.source_field_id)))}</th><td>${val(f.expected)}</td><td>${val(f.actual)}</td><td>${pill(f.comparison, string(f.comparison))}</td></tr>`).join("")}</tbody></table></div>`).join("")}<details><summary>Failed branch state and predecessor actions</summary>${renderState(failure.state)}<ol>${records(failure.actions_before).slice(0, 128).map(action => `<li>${esc(actionTitle(action.action))}</li>`).join("")}</ol></details></details>`;
}

function renderIssues(report: LocatedRecord, caseId: string, h: FittingHelpers): string {
  const issues = records(report.value.issues), selected = issues.filter(i => records(i.origins).some(o => o.case_id === caseId)), others = issues.filter(i => !selected.includes(i));
  const ordered = [...selected, ...others];
  return `<section class="fit-issues"><div class="fit-section-title"><h4>Discovered issue groups</h4><span>${issues.length} in this report · ${selected.length} affect this game</span></div><p class="fit-subtle">Issues can belong to the source mapping, observation adapter, search, or engine. Their presence does not by itself establish an engine bug.</p>${ordered.slice(0, 60).map(issue => {
    const origins = records(issue.origins);
    return `<details class="fit-issue"><summary><span>${esc(string(issue.title) || label(issue.kind) || "Recorded issue")}</span>${pill(issue.component)}<span>${origins.length} origin${origins.length === 1 ? "" : "s"}${selected.includes(issue) ? " · this game" : ""}</span></summary><p>${pill(issue.kind)} <code>${val(issue.issue_id, 100)}</code></p><ul>${origins.slice(0, 100).map(origin => `<li><button class="text-button" data-case="${esc(origin.case_id)}">${esc(h.caseTitle(string(origin.case_id)))}</button><span> · source row ${val(origin.source_row_index)}</span><p>${val(origin.detail, 2000)}</p><p class="fit-origin-columns">${array(origin.source_columns).slice(0, 40).map(column => `<code>${esc(column)}</code>`).join(" ")}</p>${h.artifact(origin.result_id, "Origin result")}${origin.evidence ? `<details><summary>Recorded issue evidence</summary><pre>${val(origin.evidence, 8000)}</pre></details>` : ""}</li>`).join("")}</ul>${origins.length > 100 ? '<p>Showing 100 origins. Inspect the report for every origin.</p>' : ""}</details>`;
  }).join("") || '<p class="fit-trace-note">No issues were recorded in this report. This is not an acceptance decision.</p>'}${ordered.length > 60 ? `<p class="fit-subtle">Showing 60 of ${ordered.length} issue groups. The report retains every group and origin.</p>` : ""}</section>`;
}
export function renderFittingComparison(context: FittingContext, caseId: string, h: FittingHelpers): string {
  return renderAttributions(context, caseId, h) + context.comparisons.filter(c => records(c.value.rows).some(r => r.case_id === caseId)).map(comparison => {
    const c = comparison.value, row = records(c.rows).find(r => r.case_id === caseId)!;
    const scopeChanges = records(c.scope_changes).filter(change => !change.case_id || change.case_id === caseId);
    const allIssues = context.reports.flatMap(r => records(r.value.issues));
    const issueName = (id: unknown) => string(allIssues.find(i => i.issue_id === id)?.title) || string(id);
    return `<section class="fit-repair"><div class="fit-section-title"><h4>Recorded before / after comparison</h4>${pill(c.assessment)}</div><p>This comparison records changes in discovery results. Acceptance, if any, is a separate factory decision.</p><div class="fit-before-after"><div><span>Before</span><strong>${esc(fittingStatus(row.before_status))}</strong><p>Coverage: ${esc(coverageText(row.coverage_before))}</p></div><div><span>After</span><strong>${esc(fittingStatus(row.after_status))}</strong><p>Coverage: ${esc(coverageText(row.coverage_after))}</p></div></div><dl class="fit-budget">${[["resolved_issue_ids", "Diagnostic signatures no longer reported"], ["remaining_issue_ids", "Remaining issues"], ["new_issue_ids", "New issues"]].map(([key, title]) => `<dt>${title}</dt><dd>${array(row[key]).map(id => esc(issueName(id))).join("; ") || "None recorded"}</dd>`).join("")}</dl><p><strong>Change motivated by</strong>: ${array(c.origin_issue_ids).map(id => esc(issueName(id))).join("; ") || "No issue linkage recorded"}</p>${scopeChanges.length ? `<aside class="fit-scope"><strong>Changed constraint records</strong><ul>${scopeChanges.slice(0, 30).map(change => `<li><strong>${esc(label(change.kind))} · ${val(change.column ?? change.field)}</strong><p>Before: ${val(change.before, 800)}</p><p>After: ${val(change.after, 800)}</p></li>`).join("")}</ul>${scopeChanges.length > 30 ? "<p>Showing 30 changed constraint records; the comparison artifact retains every change.</p>" : ""}</aside>` : ""}${array(c.limitations).length ? `<ul>${array(c.limitations).map(limit => `<li>${val(limit, 1500)}</li>`).join("")}</ul>` : ""}<div class="fit-provenance">${h.artifact(c.change_id, "Recorded patch")}${h.artifact(c.baseline_report_id, "Baseline report")}${h.artifact(c.candidate_report_id, "Candidate report")}${h.artifact(comparison.id, "Comparison record")}</div></section>`;
  }).join("");
}

function renderAttributions(context: FittingContext, caseId: string, h: FittingHelpers): string {
  return context.attributions.filter(a => array(a.value.origin_case_ids).includes(caseId)).map(attribution => {
    const a = attribution.value, report = context.reports.find(r => r.id === a.baseline_report_id);
    const issues = records(report?.value.issues).filter(i => array(a.origin_issue_ids).includes(i.issue_id));
    return `<section class="fit-repair"><div class="fit-section-title"><h4>Repair attributed to discovered issues</h4>${pill(a.component)}</div><p>${val(a.authority, 1600)}</p><ul>${issues.map(i => `<li>${val(i.title, 1600)}</li>`).join("")}</ul><p>Candidate revision <code>${val(a.candidate_revision)}</code>. This attribution does not record an accepted repair.</p><div class="fit-provenance">${h.artifact(a.change_id, "Proposed patch")}${h.artifact(a.diagnosis_id, "Recorded diagnosis")}${h.artifact(a.baseline_report_id, "Origin discovery report")}${h.artifact(attribution.id, "Attribution record")}</div></section>`;
  }).join("");
}
