import pathlib,json,hashlib,datetime,subprocess,tarfile,shutil,difflib
r=pathlib.Path('/home/ubuntu/repos/phase-verifiable-loop');e=pathlib.Path('/home/ubuntu/coworld-migration-20260904/hushbringer-v10-execution');old=e/'frozen-candidate-v10';out=e/'frozen-candidate-v10-final'
def h(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def dump(p,x):p.write_text(json.dumps(x,indent=2)+'\n')
v=e/'battle-siblings-baseline-2/receipt.json';vs=json.loads(v.read_text());assert (v.parent/'done').exists();assert len(vs['results'])==6 and all(x['exit']==0 and not x['changed'] for x in vs['results']);full=vs['results'][4];assert '187 passed; 0 failed; 20 ignored' in pathlib.Path(full['log']).read_text()
files=sorted(set(subprocess.check_output(['git','ls-files','--cached','--others','--exclude-standard','crates','Cargo.toml','Cargo.lock','rust-toolchain.toml','.cargo'],cwd=r,text=True).splitlines()));files=[f for f in files if (r/f).is_file()];manifest={f:h(r/f) for f in files};previous=json.loads((old/'source.json').read_text());assert len(manifest)==2051 and set(previous)==set(manifest)
changed=[f for f in files if previous[f]!=manifest[f]];f='crates/engine/tests/integration/trigger_suppression_event_timing.rs';assert changed==[f]
with tarfile.open(old/'source.tar.gz') as tar:original=tar.extractfile(f).read()
current=(r/f).read_bytes();assert current.startswith(original),'earlier fixture bytes changed';delta=current[len(original):];assert delta.count(b'#[test]')==3
out.mkdir(exist_ok=False);dump(out/'source.json',manifest);assert h(out/'source.json')==full['source_manifest_sha256'];archive=pathlib.Path(full['source_archive']['path']);assert h(archive)==full['source_archive']['sha256'];shutil.copyfile(archive,out/'source.tar.gz')
patch=''.join(difflib.unified_diff(original.decode().splitlines(keepends=True),current.decode().splitlines(keepends=True),fromfile='a/'+f,tofile='b/'+f));(out/'from-proof-v10.patch').write_text(patch)
fullpatch=subprocess.check_output(['git','diff','--binary'],cwd=r)
for f in subprocess.check_output(['git','ls-files','--others','--exclude-standard'],cwd=r,text=True).splitlines():
 if f in files:fullpatch+=subprocess.run(['git','diff','--no-index','--binary','--','/dev/null',f],cwd=r,stdout=subprocess.PIPE).stdout
(out/'candidate.patch').write_bytes(fullpatch)
lineage={'previous_manifest':str(old/'source.json'),'previous_manifest_sha256':h(old/'source.json'),'previous_archive_sha256':h(old/'source.tar.gz'),'final_manifest_sha256':h(out/'source.json'),'all2051_files_accounted':True,'unchanged_files':2050,'changed_file':changed[0],'complete_previous_integration_module_prefix_identical':True,'previous_fixture_prefix_sha256':hashlib.sha256(original).hexdigest(),'appended_bytes_sha256':hashlib.sha256(delta).hexdigest(),'appended_named_tests':['public_battle_attacked_invalid_protector_is_unchanged_at_sba_boundary','public_battle_phased_out_invalid_protector_is_ignored_at_sba_boundary','public_battle_unattacked_phased_in_invalid_protector_selects_living_opponent'],'production_unchanged':True,'existing_fixtures_and_helpers_unchanged':True,'proof_compilation_policy':'All mutation records retain their actual frozen v9/overlay-1/v10 compilation source. Appending these independent Battle controls is certified by fresh exact test and full-matrix runs; no old binary is relabeled as final-source compilation.','baseline_receipt':str(v),'baseline_receipt_sha256':h(v),'full_matrix_pass':187,'full_matrix_ignored':20,'new_exact_controls_pass':3}
dump(out/'proof-lineage.json',lineage)
receipt={'utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'checkout':str(r),'base':subprocess.check_output(['git','rev-parse','HEAD'],cwd=r,text=True).strip(),'files':2051,'source_manifest_sha256':h(out/'source.json'),'source_archive_sha256':h(out/'source.tar.gz'),'candidate_patch_sha256':h(out/'candidate.patch'),'proof_v10_delta_sha256':h(out/'from-proof-v10.patch'),'lineage_sha256':h(out/'proof-lineage.json'),'validation_receipt_sha256':h(v),'source_frozen':True,'full_final_gates':'running separately in final-gates-2; not presumed complete','plan_sha256':'90ae9f6e71f08661db71cce7805b334b5df2a8cf28ccd525f521f8be7a89d04a','review_sha256':'15ec8a03f9780b996368b72039f051c279d0b833e0ca6e3e6b9f3745d92f6b97'}
dump(out/'receipt.json',receipt)
for q in out.iterdir():q.chmod(0o444)
print(json.dumps(receipt,indent=2));print('receipt_sha256',h(out/'receipt.json'))
