import pathlib,json,hashlib,tarfile,datetime,subprocess,collections
P=pathlib.Path("/home/ubuntu/coworld-migration-20260904");O=P/"hushbringer-review-v10-final";M=P/"hushbringer-v10-map-correction";C=P/"hushbringer-v10-citation-fix";R=pathlib.Path("/home/ubuntu/repos/phase-verifiable-loop")
def sha(p):
 h=hashlib.sha256()
 with open(p,"rb") as f:
  for b in iter(lambda:f.read(4*1024*1024),b""):h.update(b)
 return h.hexdigest()
def save(n,v):(O/n).write_text(json.dumps(v,indent=2)+"\n")
assert sha(M/"reviewed-map-selection.json")=="2b23a1700df9eaf91eeea860ea632751878d03fbad6f37324195db16f5abe78c"
assert sha(M/"manifest.json")=="d2d753c2310393fe73dca4bc6fddd9c7be49a8826a8092e2565708678f602ccf"
assert sha(M/"handoff.json")=="f0e5744103cef14322ae87d625cbe8fb3ae4218bc4c85cbec4a7297d61fe3709"
assert sha(M/"receipt.json")=="fb1ba8d80f60213cac71a447d428a780b6458ee8723c30db128b2abb2f7f733d"
meta=json.loads((M/"manifest.json").read_text())
for f,h in meta.items():assert sha(M/f)==h
sel=json.loads((M/"reviewed-map-selection.json").read_text())
for item in sel["artifact_bindings"].values():assert sha(item["path"])==item["sha256"]
old=json.loads((C/"production-path-maintainer-map.json").read_text());new=json.loads((M/"production-path-maintainer-map.json").read_text());delta=[]
assert len(old["rows"])==len(new["rows"])==67
for i,(a,b) in enumerate(zip(old["rows"],new["rows"])):
 for k in set(a)|set(b):
  if a.get(k)!=b.get(k):delta.append(dict(row=i,id=b["id"],field=k,old=a.get(k),new=b.get(k)))
assert {(d["row"],d["field"]) for d in delta}=={(i,k) for i in [63,64] for k in ["production_entry","first_reaching_branch"]}
assert all(a["evidence"]==b["evidence"] for a,b in zip(old["rows"],new["rows"]))
assert {k for k in new if k!="rows" and new[k]!=old.get(k)}=={"utc","status","authoritative_maps","supersedes"}
source=json.loads((C/"frozen-source/source.json").read_text());assert len(source)==2051
for f,h in source.items():assert sha(R/f)==h,(f,h)
hand=json.loads((M/"handoff.json").read_text());archive=pathlib.Path(hand["source_archive"]["path"]);assert sha(archive)==hand["source_archive"]["sha256"]
with tarfile.open(archive) as tf:
 names={m.name.removeprefix("./"):m for m in tf.getmembers() if m.isfile()}
 assert set(names)==set(source)
 for f,h in source.items():assert hashlib.sha256(tf.extractfile(names[f]).read()).hexdigest()==h
assert subprocess.check_output(["git","rev-parse","HEAD"],cwd=R,text=True).strip()=="2dec6c88915db4697706234a7ba2fcedd97b1689"
assert sha(O/"live-candidate.patch")==sha(C/"frozen-source/candidate.patch")
metadata=dict(authoritative_selector={"path":str(M/"reviewed-map-selection.json"),"sha256":sha(M/"reviewed-map-selection.json")},handoff={"path":str(M/"handoff.json"),"sha256":sha(M/"handoff.json")},sealed_package_manifest_sha256=sha(M/"manifest.json"),sealed_package_files=len(meta),checked_bindings=sel["artifact_bindings"],delta=delta,all_67_evidence_payloads_unchanged=True,all_other_row_fields_unchanged=True,source_archive_sha256=sha(archive),source_archive_files_verified=2051,final_live_source_files_verified=2051,review="Corrected routes agree with actual current fixture/helper and filter source, linked mutant runtime failures and three independently rerun exact public R3 tests. Metadata finding resolved without source or evidence edits.")
save("metadata-correction-audit.json",metadata)
proof=json.loads((O/"mutation-proof-audit.json").read_text());assert not proof["problems"]
cr=json.loads((O/"cr-complete-audit.json").read_text());assert len(cr["annotations"])==185
runtime=json.loads((O/"candidate-runtime/receipt.json").read_text());assert len(runtime["results"])==12 and runtime["native_cases_verified"]==60
original=json.loads((O/"original-runtime/receipt.json").read_text());r3=json.loads((O/"r3-runtime/receipt.json").read_text())
report={
"utc":datetime.datetime.now(datetime.timezone.utc).isoformat(),"reviewer":"/root/hushbringer_full_review_final","review_kind":"Fresh full independent implementation review; no source edit, build, commit, push or acceptance approval","maintainer_simulation_gate":"PASS","cr_gate":"PASS","findings":[],
"source":{"checkout":str(R),"base":"2dec6c88915db4697706234a7ba2fcedd97b1689","branch":"codex/hushbringer-simultaneous-death","manifest_sha256":sha(C/"frozen-source/source.json"),"candidate_patch_sha256":sha(C/"frozen-source/candidate.patch"),"changed_paths":30,"source_files":2051,"prior_compiled_source_manifest_sha256":runtime["compiled_source_manifest_sha256"],"exact_lineage":"2050 source files unchanged; inverse CR608.2d→CR115.1 in one comment restores the entire remaining predecessor file byte for byte. No executable/test semantics changed; preserved fdc9 executable is not a new-source compilation."},
"inputs":{"approved_plan_sha256":sha(P/"hushbringer-plan-v10.md"),"approved_plan_review_sha256":sha(P/"hushbringer-plan-review-v10.md"),"original_handoff_sha256":sha(C/"handoff.json"),"current_handoff_sha256":sha(M/"handoff.json"),"current_authoritative_selector_sha256":sha(M/"reviewed-map-selection.json"),"current_maintainer_map_sha256":sha(M/"production-path-maintainer-map.json"),"rules_sha256":sha(R/"docs/MagicCompRules.txt")},
"audit":{"complete_plan_lines":868,"full_diff_reviewed":True,"all_affected_source_and_tests_reviewed":True,"all_authoritative_maps_reviewed":True,"record_constructor_expressions":82,"record_production_constructors":3,"record_test_constructors":79,"record_named_expressions":81,"record_self_expressions":1,"raw_record_occurrences":92,"nonconstructor_occurrences":11,"physical_scope_callsites":51,"common_boundary_rows":11,"native_unaffected_arms":3,"distinct_mutation_rows":67,"public_mutation_rows":56,"private_helper_schema_rows":10,"defensive_mutation_rows":1,"linked_mutation_logs_independently_read_and_hash_checked":409,"all_linked_counts_and_reached_failure_excerpts_reconciled":True,"immutable_evidence_paths_rehashed":2269,"immutable_evidence_mismatches":0,"historical_mutable_target_reference_records":146,"historical_mutable_target_note":"Historical identities remain receipt claims and are excluded from the 2269 immutable checks. No current historical target-byte identity is inferred.","cr_annotations":185,"added_cr_lines":156,"adjacent_cr_annotations":29,"actual_cited_rules":101,"outside_engine_manual_record_or_component_constructors":0},
"independent_runtime":{"original_worker_sha256":original["worker_sha256"],"original_three_scenarios":"Hush-first1 Spirit; Traveler-first1 Spirit; no-Hush1 Spirit, all reached actual graveyard outcomes and completed observations.","candidate_executable_sha256":runtime["executable_sha256"],"candidate_three_primary_scenarios":"Hush-first0 Spirit; Traveler-first0 Spirit; no-Hush1 Spirit.","candidate_exact_tests_passed":12,"candidate_ignored":0,"native_functions":9,"native_cases":60,"supplementary_r3_exact_tests_passed":3,"supplementary_r3_ignored":0,"fresh_compilation":False,"provenance":"Actual preserved fdc9 binary, correct engine package cwd and recorded original Cargo/runtime environment; actual system loader libraries hashed. Original e4 worker and39 original harness source files verified. No shared build target modified."},
"semantic_review":["Reusable event-production ownership and clause-local consumption; no card-name patch. The class covers multi-target Destroy/Wrath, chosen sacrifice components and mass zone moves, with SBA/Haunt/Unattach siblings.","Before uses functioning live subject relations at actual action entry; after uses completed actual record and functioning post-group sources. Some(empty) is authoritative; None remains explicitly legacy or unavailable. Ordinary/delayed ambiguity compatibility and destination self-arrival stay distinct.","ObjectId plus incarnation, top-binding barriers and exact event offset/turn-index claims prevent descendant or repeated-ID authority theft. Completed owners finalize before continuation/pause/Err return; serializer omits lexical scope. Intrinsic/nested incomplete worlds remain declared None.","Deferred selected cost invocations bind canonical component provenance before append. Clone/serde/normalization preserve it; public preflight and both finalizers reject unknown nonempty provenance before new payment. Existing actor/debug/concede authority remains effective.","Native Hand/Library/Dig choices reach real constructors and three placement arms, with60 exact order/Hush/origin cases. No fabricated pending choice or battlefield rewrite is used to claim native reachability.","Record constructors, all consumers, generated data and external serialized boundaries preserve honest optional defaults. No parser variants, card data, support allowlists, frozen corpus or checker changed."],
"resolved_findings":[{"severity":"LOW","issue":"Authoritative R3 route prose described temporary boosting and bounce, contradicting the actual static-grant/Graveyard fixture.","resolution":"Artifact author corrected exactly four production_entry/first_reaching_branch prose fields in two rows; independently verified all67 evidence payloads and engine/test source remain identical. Current map/selector/handoff are versioned; old artifacts preserved."}],
"verification_reuse":{"method":"Risk-scaled exact comment-only source lineage; not a fresh full suite execution by this reviewer.","focused":"196 pass/20 ignored","library":"16586 pass/7 ignored","integration":"3172 pass/22 ignored","binary":"15 pass","doctests":"0 executed/7 ignored","cross_source_batch_guards":"5 pass; behavioral only","engine_all_target_clippy":"pass","card_generation":"35802 cards/2870 tokens; generated tracked sources restored","workspace_clippy":"Known baseline manabrew-compat SetFullControl E0004 only","diagnostic_ignored_explicit_run":"2 pass/18 fail; never counted as repaired coverage"},
"limitations":["All ten approved rule limitations remain: aggregate grouping, inherited-target grouping, direct delayed suppression, full cross-pause grouping, ambiguous origins, intrinsic merge/nested layer worlds, co-dying off-zone Any source availability, aggregate paid continuation, cast-created regeneration persistence, resumed duplicate dispatch.","Twenty ignored desired diagnostics are excluded. Exactly-two no-Hush resumed explicit-target payoff is narrow inherited compatibility; ordinary no-Hush control remains exactly one.","Seeded regeneration covers first application only. Empty tracked-choice life23 versus selected22 remains inherited compatibility.","Zero-opponent Battle is defensive-only; public terminal/legal/multiple-choice/attacked/phased siblings do not establish that zero-choice runtime branch. Inherited non-Siege pending-stack/present-protector behavior is unclaimed.","No parser/data/card coverage promotion or throughput claim. None fallback can rescan functioning sources; missing historical benchmark input remains unavailable.","Final committed-source worker compilation, frozen-checker comparison and independent repair acceptance approval remain later root-owned gates."],
"approval_scope":"Implementation review only. Repair acceptance not approved.","artifacts":{str(p.relative_to(O)):sha(p) for p in O.rglob("*") if p.is_file() and p.name not in {"review-report.json","review-report.md","manifest.json"}}
}
save("review-report.json",report)
(O/"review-report.md").write_text("Maintainer-Simulation Gate: PASS\nCR Gate: PASS\n\nNo outstanding findings.\n\nReviewed source SHA-256: `"+report["source"]["manifest_sha256"]+"`.\nCurrent handoff SHA-256: `"+sha(M/"handoff.json")+"`.\n\nThe factual R3 handoff wording was corrected and independently verified during this full review. This verdict does not approve repair acceptance. Full audit scope, runtime provenance, retained limitations and source/evidence hashes are in `review-report.json` and the sealed audit artifacts.\n")
manifest={str(p.relative_to(O)):sha(p) for p in sorted(O.rglob("*")) if p.is_file() and p.name!="manifest.json"}
save("manifest.json",manifest)
for p in O.rglob("*"):
 if p.is_file():p.chmod(0o444)
for f in ["review-report.md","review-report.json","manifest.json","metadata-correction-audit.json","candidate-runtime/receipt.json","original-runtime/receipt.json"]:print(f,sha(O/f))
print("SEALED",len(manifest),"files; both gates PASS; zero outstanding findings")
